compatibility_flags = ["streams_enable_constructors"]

name = "profeval"
pages_build_output_dir = "./dist"
[[d1_databases]]
binding = "DB"
database_name = "prod-profeval"
database_id = "094ebd25-9b21-4110-986c-0c9cbd417b39"
